spring:
  profiles:
    include: secret
  servlet:
    multipart:
      enabled: true
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: cookudasse
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
